"""empty message

Revision ID: 41bc71f86c61
Revises: 
Create Date: 2024-01-07 17:19:15.698910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bc71f86c61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('MachineID', sa.Integer(), nullable=False),
    sa.Column('Machine', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('MachineID')
    )
    op.create_table('material',
    sa.Column('MaterialID', sa.Integer(), nullable=False),
    sa.Column('Material', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('MaterialID')
    )
    op.create_table('machinematerial',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('MachineID', sa.Integer(), nullable=True),
    sa.Column('MaterialID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MachineID'], ['machine.MachineID'], ),
    sa.ForeignKeyConstraint(['MaterialID'], ['material.MaterialID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machinematerial')
    op.drop_table('material')
    op.drop_table('machine')
    # ### end Alembic commands ###
